apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcomputing
spec:
  selector:
    matchLabels:
      app: cloudcomputing
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: cloudcomputing
    spec:
      containers:
        - name: cloudcomputing
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
       - name: mysecretname
