name: Java CI with Maven

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: List build directory
        run: ls -al ./target
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ./cloudcomputing/target/cloudcomputing-0.0.1-SNAPSHOT.jar