name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/build.yaml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: "success()"
    steps:
      - name: Deploy
        uses: ./.github/workflows/docker-publish.yaml