name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    steps:
      -
      - name: Build
        uses: ./.github/workflows/build.yaml

  deploy:
    needs: build
    if: success()
    uses: ./.github/workflows/docker-publish.yaml