name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print directory
        run: ls -al
      - name: Build
        uses: ./.github/workflows/build.yaml

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloudcomputing
    needs: build
    if: success()
    steps:
      - uses: ./.github/workflows/docker-publish.yaml